terminei a lição por completa. Mas ficou um bug no meu código no ReportCardTest.class, nos métodos testKeys(), testValues(), testEntries(). Primeiro problema que tinha dado foi o do getMessages() que ele tava querendo que o getMessages() fosse não privado, então coloquei para publico e resolvi o problema, até então. Logo em seguida, quando eu testei novamente deu outro problema, que foi o que o card está nulo. Lá na página 483, ele pedi para eu criar um setUp() e uma variavel e instaciar ela no setUp. eu fiz, só que pelo que parece ela não está sendo chamada. OBS: TERMINEI A LIÇÃO CHEGUEI NO EXERCICIO, POREM AINDA TO COM ESSE BUG DAS PÁGS:485 À 489.
PROBLEMA RELATADO:
java.lang.NullPointerException: Cannot invoke "sis.report.ReportCard.getMessages()" because "this.card" is null